type Product {
  name: String!
  description: String!
  collection: Collection
  price: Float!
  colors: [String!]!
  mainImage: String!
  otherImages: [String!]
  category: String!
  sizes: [String!]
  created_at: Date!
  active: Boolean
}

type Collection {
  name: String!
  description: String
  created_at: Date!
  active: Boolean
  featured: Boolean
  products: [Product!]! @relation
}

type FAQ {
  title: String!
  icon: String!
  list: [FAQuestion!]! @relation
}

type FAQuestion {
  question: String!
  answer: String!
}

type Query {
  allCollections: [Collection!]
  allProducts: [Product!]
  collections(featured: Boolean): [Collection!]
  allFAQCategories: [FAQ!]
  allFAQuestions: [FAQuestion!]
}
