type Product {
    name: String!
    description: String!
    collection: Collection
    price: Float!
    colors: [String!]!
    imageURIs: [String!]!
    category: String!
    size: String!
    created_at: Date!
    active: Boolean
}

type Collection {
    name: String!
    description: String
    created_at: Date!
    active: Boolean
    products: [Product!]! @relation
}

type Query {
    allCollections: [Collection!]
    allProducts: [Product!]
}

