type Product {
    name: String!
    description: String!
    price: Float!
    color: [String!]!
    imageURIs: [String!]!
    category: String!
    collection: String
    size: String!
    created_at: Date!
    active: Boolean
}

type Query {
    allProducts: [Product!]!
}
